apiVersion: v1
kind: Service
metadata:
  labels:
    app: TeamManagementSystemsrv
    service: TeamManagementSystemsrv
  name: TeamManagementSystemsrv
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: TeamManagementSystem